name: Lint

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn install --force

    - name: Run eslint
      run: yarn run lint:ts
      if: always()

    - name: Run stylelint
      run: yarn run lint:scss
      if: always()

    - name: Run jest
      run: yarn run test:unit
      if: always()
