name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Build project
      run: npm run build:prod

    - name: Install Netlify CLI
      run: npm install netlify-cli -g

    - name: Deploy to Netlify
      run: netlify deploy --dir=build --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STORYBOOK_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}

    